### ISSUE TITLE
Request: Please release the whole source code

### ISSUE THREAD

**Issue by Samurai1201** [PearXP/esp32-web-server-status#2]
I really like your project, but am a bit nervous about running binaries, where i cant check the code myself 

I would really appreciate it, also because i would like to add NTFY as a notification system

Thanks a lot

**Comment by PearXP** [comment]
Hi, I’ll share the code later. It’s a bit messy right now, so I need to tidy it up. I really like your idea with NTFY; I was also looking for an app like that. I’ll integrate it in the next updates. Thank you!

**Comment by PearXP** [comment]
Hello, I have uploaded the source code and added the ntfy integration in V0.1.1 . If you discover any errors, feel free to contact me. :)

**Comment by Samurai1201** [comment]
Thanks a lot :)
